import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Content = IContentItem<{
  local_slug: Elements.UrlSlugElement;
  content_tags: Elements.TaxonomyElement;
  text_3960151: Elements.RichTextElement;
  content_type: Elements.TaxonomyElement;
  url: Elements.TextElement;
  cover_image: Elements.AssetsElement;
  cover_image_url: Elements.TextElement;
  title: Elements.TextElement;
  teaser: Elements.RichTextElement;
  date: Elements.DateTimeElement;
}>;
